### ISSUE TITLE
Consider switching the authorization mode from ABAC to RBAC

### ISSUE THREAD

**Issue by frodenas** [cloudfoundry-incubator/kubo-release#104]
The kubernetes-apiserver [control script](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-api/templates/bin/kubernetes_api_ctl.erb#L49) harcodes [ABAC](https://kubernetes.io/docs/admin/authorization/abac/) as the kubernetes authorization mode. ABAC is difficult to manage as the API server must be restarted in order to apply any change to the [policy file](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-api/templates/config/authorization_policy.jsonl.erb). OTOH, [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/) permission policies are configured using kubectl or the Kubernetes API directly, without the need to modify the manifest (and to restart the api server). ABAC, also, is starting to be considered [legacy](https://github.com/kubernetes/kubernetes/search?q=abac+legacy&type=Issues&utf8=%E2%9C%93) on versions > 1.6.

Can you please consider switching the authorization mode from ABAC to RBAC? Or at least, make it configurable so those of use who want to use RBAC can enable it via manifest?

**Comment by mordebites** [comment]
We're waiting for the PMs to prioritise this.
