### ISSUE TITLE
kubernetes-controller-manager failing to start when running on bosh-lite

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/kubo-release#109]
When deploy kubo-release 0.7.0 on bosh-lite the master nodes are not able to start (more specifically the kubernetes-controller-manager job). 

Logs below:
```
==> /var/vcap/sys/log/kubernetes-controller-manager/kubernetes_controller_manager_ctl.stderr.log <==
+ declare pid=5750
+ ps -p 5750
+ __log 'Removing stale pidfile'
+ echo 'Removing stale pidfile'
+ rm /var/vcap/sys/run/kubernetes/kubernetes_controller_manager.pid
+ echo 5760
+ start_kubernetes_controller_manager
+ '[' -f /sys/class/dmi/id/product_serial ']'
+ chmod a+r /sys/class/dmi/id/product_serial
chmod: changing permissions of '/sys/class/dmi/id/product_serial': Read-only file system

==> /var/vcap/sys/log/kubernetes-controller-manager/kubernetes_controller_manager_ctl.stdout.log <==
------------ STARTING kubernetes_controller_manager_ctl at Tue Sep 12 07:32:00 UTC 2017 --------------
Removing stale pidfile
```

I was able to work around the issue by, during a bosh deploy, removing the [following line](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-controller-manager/templates/bin/kubernetes_controller_manager_ctl#L38) from the control script (by using bosh ssh and vi).

**Comment by akshaymankar** [comment]
@rkoster Thanks for reporting this, but unfortunately we don't support bosh-lite as of now. We may support it in future releases.

I have added a feature in our icebox here: https://www.pivotaltracker.com/story/show/151084110

**Comment by gregpatricio** [comment]
Update: Kubo can now run on Bosh Lite
