### ISSUE TITLE
Kubo 0.7.0: missing file in kubo-deployment/manifests/ops-files/ - k8s_master_static_ip_vsphere.yml

### ISSUE THREAD

**Issue by guillierf** [cloudfoundry-incubator/kubo-release#110]
In the last pull of kubo-deployment (git clone https://github.com/cloudfoundry-incubator/kubo-deployment), the following file is missing in /root/kubo-deployment/manifests/ops-files/:
k8s_master_static_ip_vsphere.yml

content of the file:
- type: replace

  path: /networks/type=manual/subnets/0/static

  value:

  - ((kubernetes_master_host))

result is without this while, K8s cluster deployment fails (when a static IP for Master node is specified).

Can you push the file in the repository?
thanks

**Comment by bstick12** [comment]
@guillierf 

The file was renamed to k8s-haproxy-static-ips-vsphere.yml - https://github.com/cloudfoundry-incubator/kubo-deployment/blob/58aa7db3e1caddddd29a6d07759aeb332e36e249/manifests/ops-files/k8s-haproxy-static-ips-vsphere.yml

Are you seeing a reference to the old name somewhere?

**Comment by guillierf** [comment]
@bstick12 
thanks !
I didn't know for the renaming.

No, I don't see a reference to the old name anywhere.
I was using some customized scripts (home made) and I was using this particular name.

We can close the ticket.
problem solved!
