### ISSUE TITLE
Password escapes

### ISSUE THREAD

**Issue by svrc-pivotal** [cloudfoundry-incubator/kubo-release#125]
Just to capture this as a possible docs fix or code fix:

- passwords with a % in them are susceptible to a Golang parsing error, this is likely a bug in the ODB broker code or service adapter but I haven’t tracked it down yet, it might be also in Kubo-release itself but I haven’t confirmed.  Can be worked around with “%%” if the bug is triggered.  See https://github.com/cloudfoundry/bosh-cli/issues/330 for details

- passwords with backslashes (“\”) for vsphere need to be escaped in one spot and not escaped in a different spot - see this PR https://github.com/cloudfoundry-incubator/kubo-release/pull/121 for one solution.

**Comment by glestaris** [comment]
hey @svrc-pivotal,

Have you confirmed if the Kubo-Release is also subject to the behaviour you described? If so, can you please provide us with steps to reproduce?

**Comment by svrc-pivotal** [comment]
Hi @glestaris , the vsphere one I think is being incorporated as my PR https://mail.google.com/mail/u/0/#search/kubo-release/15f875f657283f79

the double %% is only on the ODB, having to do with the way it generates manifests.   I can close this an file a ticket on that repo now that the vsphere permission issue is being fixed here.

**Comment by glestaris** [comment]
Hey @svrc-pivotal, the link you posted above does not work for me... Seems like a link to Gmail?

**Comment by svrc-pivotal** [comment]
@glestaris updated, too many tabs open ;)

**Comment by glestaris** [comment]
thanks @svrc-pivotal. I scheduled the PR: https://www.pivotaltracker.com/story/show/151965138.

**Comment by glestaris** [comment]
https://github.com/cloudfoundry-incubator/kubo-release/pull/121 is not merged. Closing this. Feel free to reopen if not done.
