### ISSUE TITLE
HTTP proxy for kube-controller-manager

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry-incubator/kubo-release#126]
Hi guys

We need to set `http_proxy` (and `no_proxy`) for the `kube-controller-manager` binary. 
Use case: `kube-controller-manager` talks to external systems (i.e. to the Cloud API for storage provision) which are behind a proxy in our environment.

This is currently not possible with the BOSH release - we'd like to add this config item to the release. 

This basically means to add `export http_proxy=<%= p('http_proxy') %>` (and `no_proxy`) before launching the binary in [kubernetes_controller_manager_ctl](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-controller-manager/templates/bin/kubernetes_controller_manager_ctl).

Before I create a PR I have some questions:

- Would you welcome it?
- For which jobs shall we expose the proxy? We only need it for the `kube-controller-manager` job, however, for consistency, it should probably be added for all jobs that interact with external systems
- Shall I also create a PR for [kubo-deployment](https://github.com/cloudfoundry-incubator/kubo-deployment)? If yes, should I reuse the already existing [`env.http_proxy`](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/b3b44f76507f79570cc29a11ee49030aa1d342a2/bosh-deployment/misc/proxy.yml#L4) that is used for BOSH?

**Comment by glestaris** [comment]
hey @MatthiasWinzeler. Your use case and proposed PR sound very reasonable. Please proceed and we will be happy to review/merge.

**Comment by MatthiasWinzeler** [comment]
hi @glestaris 
created the PR #130 
We figured out that not only the `kubernetes-controller-manager` interacts with the cloud provider, but also other jobs do. 

Disclaimer: The PR is just a quick & dirty way to get it running for us, it probably needs some polishing - let's consider it a discussion basis :)

Also, these vars need to be exposed in `kubo-deployment` as well, but we can create a PR there if this is merged.
Thank you!

**Comment by glestaris** [comment]
https://github.com/cloudfoundry-incubator/kubo-release/pull/130 is merged.
