### ISSUE TITLE
kubelet jobs prestart script does not work on vsphere with multiple datacenters

### ISSUE THREAD

**Issue by jostockley** [cloudfoundry-incubator/kubo-release#127]
The kubelet job prestart script needs to add
`export GOVC_DATACENTER="$(get_cloud_property "datacenter")"`
otherwise on vcenter with more than one datacenter defined the kubelet job deployment fails. Examining the logs in worker/0 reveals:
`/var/vcap/packages/govc/bin/govc: default datacenter resolves to multiple instances, please specify
`
I am using kubo-release build 0.9.0-dev.21 as provided by downloading kube-deployment-latest.tgz

**Comment by glestaris** [comment]
This is interesting. We can have a look. We would be open to a PR as well.

**Comment by jostockley** [comment]
Trying to get contributor license agreement signed/submitted. If successful, I'll create a PR

**Comment by bsnchan** [comment]
Hey @jostockley - did you ever get around to signing the CLA? We'd love a PR for this.
