### ISSUE TITLE
cni package uses distro specific files

### ISSUE THREAD

**Issue by ppadmavilasom** [cloudfoundry-incubator/kubo-release#128]
Found this while compiling release for photonos. 

Running packaging script: Command exited with 127; Stdout: , Stderr: + mkdir -p /var/vcap/packages/cni/bin\n+ tar -xzf cni/cni-amd64-v0.5.2.tgz -C /var/vcap/packages/cni/bin/\n+ mkdir -p utillocal\n+ dpkg -x cni/util-linux_2.27.1-6ubuntu3_amd64.deb utillocal/\npackaging: line 7: dpkg: command not found\n"

photon does not have dpkg but i was wondering if this packaging is right 

From https://github.com/cloudfoundry-incubator/kubo-release/blob/master/packages/cni/packaging
dpkg -x cni/util-linux*.deb utillocal/
cp utillocal/usr/bin/nsenter ${BOSH_INSTALL_TARGET}/bin

shouldnt nsenter be built for the target platform rather than copying from a distro specific package?

**Comment by bsnchan** [comment]
Hi @ppadmavilasom,

We have only been testing our releases against the Ubuntu stemcell. We can talk to our PMs to see if we'd like to make our release compatible with other distros. We'd also be open to a pull request.

**Comment by bsnchan** [comment]
Hi @ppadmavilasom - is this still an issue for you? We have been focusing on testing against the Ubuntu stemcell only. Please feel free to submit a PR if this is something you need.
