### ISSUE TITLE
Perhaps change apply-specs to a post-start rather than errand

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/kubo-release#133]
I'm trying to deploy v0.9.0. The `kubelet` job complains that `User "kubelet" cannot create nodes at the cluster scope`. I see in master branch there is a new `apply-specs` but it looks like an errand. I think this will mean the `kubelet` job still still not have user credentials because the `apply-specs` errand will not have been run yet.

But I'm new so I'm probably still missing something. I thought I'd raise this issue as a basis for discussion and discovery.

**Comment by bsnchan** [comment]
Hi @drnic,

Which authorization mode have you set in your director.yml? Can you provide more detail on how you got the kubelet error message?

The apply-specs errand only applies additional workloads if they are specified in the director.yml but the kubelet user should already have the correct credentials it needs (https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-system-specs/templates/config/rbac_policy.yml.erb#L15-L27).

**Comment by drnic** [comment]
I eventually figured out my CFCR deployment and the internal bits all talk happily with each other. Closing.
