### ISSUE TITLE
curl --fail prevents error messages being displayed in logs

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/kubo-release#135]
I am trying to get CF/TCP routing enabled, but `bosh deploy` errors saying `Review logs for failed jobs: kubernetes-api-route-registrar`. So I look at the logs but there are no error messages:

```
==> /var/vcap/sys/log/kubernetes-api-route-registrar/trace_announce_route.log <==
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:7): main(): PATH=/var/vcap/packages/jq/bin/:/bin:/usr/bin:/sbin:/usr/sbin
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:10): main(): UAA_API_URL=https://uaa.18-220-96-60.sslip.io
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:11): main(): UAA_CLIENT_ID=routing_api_client
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:12): main(): UAA_CLIENT_SECRET=xxx
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:13): main(): CLOUD_FOUNDRY_API_URL=https://api.18-220-96-60.sslip.io
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:14): main(): BACKEND_PORT=8443
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:15): main(): BACKEND_IP=10.10.1.241
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:16): main(): KUBO_PORT=8443
++22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:19): main(): curl --fail --max-time 10 -s -k -X POST https://uaa.18-220-96-60.sslip.io/oauth/token --data 'client_id=routing_api_client&client_secret=xxx&grant_type=client_credentials&response_type=token'
+22:46:22 (/var/vcap/jobs/kubernetes-api-route-registrar/bin/announce_route:19): main(): UAA_REQUEST=
```

This comes from https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kubernetes-api-route-registrar/templates/bin/announce_route.erb#L19-L20

I understand the use of `curl --fail` so we can nicely get the output into the `$UAA_REQUEST` variable. But on the downside, we are throwing away the error message.

Since the instructions for configuring the UAA client are manual in https://docs-cfcr.cfapps.io/installing/cf-routing/#step-3-configure-cfcr-for-cloud-foundry-routing there is a high chance of humans getting this wrong (e.g. me).

I would like to strongly advocate for us returning the UAA API error into the logs if there is one.

Perhaps run `curl --max-time 10 -s -k -X POST https://uaa.18-220-96-60.sslip.io/oauth/token --data 'client_id=routing_api_client&client_secret=xxx&grant_type=client_credentials&response_type=token` without the `--fail` first, harmlessly printing the output to the logs if its successful, but helpfully printing the logs if its an error. And then run it again inside `UAA_REQUEST=$(curl --fail ...)`.

**Comment by glestaris** [comment]
This has been done. Closing.
