### ISSUE TITLE
`kubernetes-api` job restarts when no GCP service account is assigned to master

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/kubo-release#137]
We were testing using service keys for GCP CFCR to run without changes to the cloud config.

We have removed service-accounts from cloud-config. Master VM started and was shown as a `running` but then crashed. 
It was changing state all the time and was restarting every 30 seconds.
`kubernetes-api` and `kubernetes-controller-manager` jobs were failing. It would be nice if deployment failed on this step and not during post-deploy step.

**Comment by Manifaust** [comment]
Thanks we'll talk about improving this health check.

**Comment by bsnchan** [comment]
@glestaris this is probably something we want to do to improve all our health checks

**Comment by glestaris** [comment]
@alex-slynko according to https://www.pivotaltracker.com/story/show/154312485:

> When having empty service account values, the failure is less prominent. Some services on the VMs are flapping, e.g. kube-apiserver and kubelet. In our case, the master vm deployment succeeded, but the worker vm deployment failed.

Is this not what you are seeing?
