### ISSUE TITLE
InfluxDB is exposed via NodePort, but it should not

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/kubo-release#138]
InfluxDB is used only by Kubernetes dashboard and is exposed via NodePort for some reason. 
Community spec uses unexposed InfluxDB https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/influxdb-service.yaml

**Comment by glestaris** [comment]
@tvs seemed to have addressed the issue. Closing this.
