### ISSUE TITLE
route-sync is leaking tickers

### ISSUE THREAD

**Issue by st3v** [cloudfoundry-incubator/kubo-release#140]
Using `time.Tick` to repeatably create new Tickers causes a slow memory leak in `pooler.timeBased.Run`. 

https://github.com/cloudfoundry-incubator/kubo-release/blob/49ca668b71f224e90ed0c767ef66e8fcffc36f3e/src/route-sync/pooler/pooler.go#L63

Following is a heap profile taken with pprof for a sample that replicates the problematic code (kept it running for a few hours):

```
(pprof) top5
Showing nodes accounting for 78.56MB, 100% of 78.56MB total
      flat  flat%   sum%        cum   cum%
   75.01MB 95.48% 95.48%    78.56MB   100%  time.NewTicker /usr/local/Cellar/go/1.9.2/libexec/src/time/tick.go
    3.55MB  4.52%   100%     3.55MB  4.52%  time.startTimer /usr/local/Cellar/go/1.9.2/libexec/src/runtime/time.go
         0     0%   100%    78.56MB   100%  main.tick /Users/switzel/go/src/github.com/st3v/tick/main.go
         0     0%   100%    78.56MB   100%  time.Tick /usr/local/Cellar/go/1.9.2/libexec/src/time/tick.go
```

You can see that we accumulated 75MB of tickers at that point, and it's only climbing. 

From the [go docs](https://golang.org/pkg/time/#Tick):

> Tick is a convenience wrapper for NewTicker providing access to the ticking channel only. While Tick is useful for clients that have no need to shut down the Ticker, be aware that without a way to shut it down the underlying Ticker cannot be recovered by the garbage collector; it "leaks". Unlike NewTicker, Tick will return nil if d <= 0.

So either use `time.NewTicker()` or better yet, don't re-assign `timer` at all. You could rewrite the function as follows:

```go
func (tb *timeBased) Run(ctx context.Context, src route.Source, router route.Router) {
    ticker := time.NewTicker(tb.interval)
    defer ticker.Stop()

    tb.tick(src, router)

    for {
        select {
            case <-ctx.Done():
                return
            case <-ticker.C:
                tb.tick(src, router)
            }
    }
}
``` 

**Site Note:** It seems `Pooler` is doing more than what its name suggests. It looks like it's concerned both with scheduling *and* actually syncing routes. Would it make sense to separate these concerns? `Pooler.Run` could just take a function, i.e. `Run(ctx context.Context, fn func())`.

Fyi @jhvhs, I mentioned this last week.

**Comment by Manifaust** [comment]
We will prioritize this in the next IPM
