### ISSUE TITLE
#kubo Slack channel does not exits

### ISSUE THREAD

**Issue by coreyti** [cloudfoundry-incubator/kubo-release#145]
[This commit](https://github.com/cloudfoundry-incubator/kubo-release/commit/64f0af98cb9fbe4fbd60f01c5ce2d1a11d1d2481#diff-04c6e90faac2675aa89e2176d2eec7d8) adds a link to the [README.md](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/README.md) directed at the "#kubo" Slack channel on https://slack.cloudfoundry.org. That channel does not exist.

**Comment by BenChapman** [comment]
Thank you for pointing this out. We have now updated the README.md. We have changed our Slack Channel to #cfcr to be in line with the new product name.
