### ISSUE TITLE
Removal of kubeconfig leaves no mechanism to retrieve the kubernetes-api-url value

### ISSUE THREAD

**Issue by carlo-colombo** [cloudfoundry-incubator/kubo-release#146]
In version `0.9.0` the kubeconfig job has a property `kubernetes-api-url` which contained the external location address for the api-server

This has been removed in `0.10.0`. This means that the external address can't be interrogated from the generated BOSH Manifest.

**Comment by Manifaust** [comment]
@carlo-colombo we have removed the `kubeconfig` job as of `0.10.0`. We want to avoid this from happening again so creating a fake property in an existing job is probably not a good idea. Is it okay to put the `kubernetes-api-url` property in a new metadata section?

**Comment by jfmyers9** [comment]
As a result of a conversation that we had as a team, we would prefer to not add an unused property.

We are going to close out this issue in the meantime. Feel free to reopen the issue if necessary.
