### ISSUE TITLE
Apply specs errand fails with empty specs

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/kubo-release#150]
When `nil` is passed, `kubectl apply` fails.
When empty string is passed, it seems that following line is going to help. 
https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/apply-specs/templates/bin/deploy-specs.erb#L19
But actually it renders empty bash function, which is can not be parsed and script fails as well.

**Comment by srm09** [comment]
Fixed with [the commit](https://github.com/cloudfoundry-incubator/kubo-release/commit/337a2de8cd28953fbd3e0d9724e161424b35841b)
