### ISSUE TITLE
kubo does not seems to be deployed to bosh.io

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/kubo-release#155]
https://bosh.io/releases/github.com/cloudfoundry-incubator/kubo-release
is empty.

any plans to fix this?

**Comment by glestaris** [comment]
Hey @ramonskie, he noticed this and asked the BOSH team. There seems to be an issue with one of the early versions of the Kubo Release (missing blob or something along these lines). https://github.com/bosh-io/releases/pull/28 should fix this by ignoring the first releases.

**Comment by glestaris** [comment]
hey @ramonskie, fixed: http://bosh.io/releases/github.com/cloudfoundry-incubator/kubo-release?all=1.
