### ISSUE TITLE
Syslog-release(-migration) unable to start with secure-var-vcap job enabled

### ISSUE THREAD

**Issue by carlo-colombo** [cloudfoundry-incubator/kubo-release#160]
It seems like the `chmod` used by the `secure-var-vcap` job is preventing the blackbox binary(syslog-forwarder-release) in `/var/vcap/packages/blackbox/bin/blackbox` from starting as syslog user.

The command that fails to run is: 
```
chpst -u syslog:syslog /var/vcap/packages/blackbox/bin/blackbox  \
    -config=/var/vcap/jobs/syslog_forwarder/config/blackbox_config.yml
```

with the error: 

```
chpst: fatal: unable to run: /var/vcap/packages/blackbox/bin/blackbox: access denied
```

Perhaps the `secure-var-vcap` job should be more granular to allow jobs like these to be able to run.

**Comment by glestaris** [comment]
Prioritised

**Comment by akshaymankar** [comment]
Closing as it is accepted in tracker.
