### ISSUE TITLE
Failed to get VM UUID on vSphere

### ISSUE THREAD

**Issue by srm09** [cloudfoundry-incubator/kubo-release#161]
While deploying Kubo v0.10.0 on a vSphere environment, the `kube-apiserver` job failed to start with the following error:
```
I0111 20:18:13.459409    8464 cloudprovider.go:59] --external-hostname was not specified. Trying to get it from the cloud provider.
E0111 20:18:13.459631    8464 vsphere.go:187] Failed to get VM UUID. err: error retrieving vm uuid: open /sys/class/dmi/id/product_serial: permission denied
error setting the external host value: "vsphere" cloud provider could not be initialized: could not init cloud provider "vsphere": error retrieving vm uuid: open /sys/class/dmi/id/product_serial: permission denied
I0111 20:18:52.768326    8974 server.go:114] Version: v1.8.4
```
Kubo was deployed as part of a PKS deployment.

On some investigation we found that the correct permissions for this file are setup as part of the `kube_controller_manager_ctl` [startup script](https://github.com/cloudfoundry-incubator/kubo-release/blob/6debbb34b0394ac9ee1ab07f8924448a5c5b170e/jobs/kube-controller-manager/templates/bin/kube_controller_manager_ctl.erb#L39). 
Moving the change of permissions to a pre-start script for the same job seems to have resolved the issue.

**Comment by glestaris** [comment]
closing since pr got merged
