### ISSUE TITLE
At least # character is not handled correctly in cloud-provider configuration

### ISSUE THREAD

**Issue by carlo-colombo** [cloudfoundry-incubator/kubo-release#171]
Hash are parsed as comment from the `gcfg` parser (the library used by kubernetes to parse cloud provider config files). Other character are possibly not correctly handled. We have requirements for password to handle at least `#&;"'^\ !%` characters in the vsphere provider.

https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/cloud-provider/templates/config/cloud-provider.ini.erb

https://github.com/cloudfoundry-incubator/kubo-release/blob/master/spec/cloud_provider_ini_spec.rb#L86

Example
=========

```go
package main

import (
	"fmt"
	"log"
	"gopkg.in/gcfg.v1"
)

func main() {
	cfgStr := `
[Global]
name=x123#$%^&*'"`

	cfg := struct {
		Global struct {
			Name string
		}
	}{}
	_ := gcfg.ReadStringInto(&cfg, cfgStr)
	fmt.Println(cfg.Global.Name)
        // => x123 instead of x123#$%^&*'"
}

```

**Comment by Manifaust** [comment]
This is being fixed, we're going to surround the password in double quotes. That also means we'll be escaping backslash and double quotes.

**Comment by Manifaust** [comment]
https://github.com/cloudfoundry-incubator/kubo-release/commit/10dac5474cb1d5061045fa6e3dd068344215a87c
