### ISSUE TITLE
vSphere password with special characters still works incorrectly

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/kubo-release#180]
I have my favourite password with `!` and `\` characters, but I can't use it with Kubo.
Pre-start script fails with the following error:
```
/var/vcap/packages/govc/bin/govc: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

After some digging, we found out that pre-start script transforms `!` character to something else.
It works much better when we changed how password is passed to the following way
```
GOVC_PASSWORD=$'#&;^\ !%\'Az1'
```
See more http://wiki.bash-hackers.org/syntax/quoting#ansi_c_like_strings

**Comment by BenChapman** [comment]
What the password looks like in VSphere: `#&;^\ !%'Az1`
