### ISSUE TITLE
GCP: Support for ability to specify manual subnet

### ISSUE THREAD

**Issue by jshah-pivotal** [cloudfoundry-incubator/kubo-release#183]
Deploying a cluster with manual subnets, the `cloud-provider.ini` needs to specify the subnetwork-name to be able to deploy
a `Service` of type `LoadBalancer` with the GCE annotation `cloud.google.com/load-balancer-type` of type `Internal`.

Without this, the IP address isn't correctly assigned on a subnet in the VPC.

The erb template
[kube-apiserver/templates/config/cloud-provider.ini.erb](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kube-apiserver/templates/config/cloud-provider.ini.erb)

doesn't have this field nor does the 
[BOSH job spec](https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/cloud-provider/spec#L14-L17)
 have an option for it.

cc @cholick

**Comment by karampok** [comment]
Hi @jshah-pivotal ,
could you elaborate a bit more the issue?

"Deploying with manual subnets", where/what is the deploying refers to? bosh?

What is the error you get? or what is the output of the kubectl commands that shows
 `the IP address isn't correctly assigned on a subnet in the VPC"

Thanks!

**Comment by jshah-pivotal** [comment]
Bosh is the one deploying with manual subnets.
This is subnet config we are talking about. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/gce/gce.go#L167 

https://github.com/cloudfoundry-incubator/kubo-release/blob/master/jobs/kube-apiserver/templates/config/cloud-provider.ini.erb#L13

add `subnetwork-name` here. 

In the logs we see that subnet name comes out empty. When loadbalancer is created there is no frontend.  It does not get IP assigned to it.

**Comment by alex-slynko** [comment]
The fix is in 0.23 release
