### ISSUE TITLE
information required

### ISSUE THREAD

**Issue by vikramhome** [cloudfoundry-incubator/kubo-release#196]
I have installed cf container runtime open source and struggling with accessing kubernetes dashboard that is probably installed with it. I could authenticate to credhub and received certain credentials for kubernetes, but can not get anything even on curl. Proabably I am not sure what all parameters to supply. Can someone please help. or suggest any tutorial for that.

**Comment by tvs** [comment]
In general questions about utilizing plain Kubernetes components would be better suited for [Slack](https://cloudfoundry.slack.com/channels/cfcr).

We _do_ deploy the Kubernetes Dashboard by default (assuming you've deployed via kubo-deployment's `deploy_k8s` script or run the `apply-addons` errand). I would recommend consulting the [kubernetes-dashboard documentation](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above) for instructions on accessing it.
