### ISSUE TITLE
kubernetes-system-spec post-start script fails

### ISSUE THREAD

**Issue by zzenoxx** [cloudfoundry-incubator/kubo-release#207]
I am trying to deploy the pivotal PKS, on a vSphere environment with NSX-T. (completely nested)

following the https://www.virtuallyghetto.com/2018/03/getting-started-with-vmware-pivotal-container-service-pks-part-1-overview.html tutorial and fully build reference architecture https://www.hanymichaels.com/2018/04/27/reference-architecture-building-an-on-premise-kubernetes-solution-with-vmware-pks-and-nsx-t/

My deployment rolls out the master and 3 workers perfectly but fails on 1 of 3 post-deploy scripts.
As this is new to me, I tried to look into the logs of the bosh task & Kube master. but I got no clue of why the kubernetes-system-spec fails.

thanks in advance.

bosh debug log (last part):
D, [2018-05-31T06:55:37 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.e291bd32-1419-4d3f-abb1-9e573552b683"}
D, [2018-05-31T06:55:37 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.e291bd32-1419-4d3f-abb1-9e573552b683 {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:38 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.2dda8375-9f9e-4b39-9a13-522efd18c783"}
D, [2018-05-31T06:55:38 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.2dda8375-9f9e-4b39-9a13-522efd18c783 {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:39 #32661] [task:120-checkpoint] DEBUG -- DirectorJobRunner: (0.000522s) BEGIN
D, [2018-05-31T06:55:39 #32661] [task:120-checkpoint] DEBUG -- DirectorJobRunner: (0.001870s) UPDATE "tasks" SET "checkpoint_time" = '2018-05-31 06:55:39.013729+0000' WHERE ("id" = 120)
D, [2018-05-31T06:55:39 #32661] [task:120-checkpoint] DEBUG -- DirectorJobRunner: (0.003349s) COMMIT
D, [2018-05-31T06:55:39 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.62bd2147-a323-47b7-a84c-ac4238aa7b93"}
D, [2018-05-31T06:55:39 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.62bd2147-a323-47b7-a84c-ac4238aa7b93 {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:40 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.2c9288d9-fac5-45c4-a06c-7095059ca9ea"}
D, [2018-05-31T06:55:40 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.2c9288d9-fac5-45c4-a06c-7095059ca9ea {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:41 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.03d439e9-93b0-4a47-b6f0-7b8195509f8a"}
D, [2018-05-31T06:55:41 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.03d439e9-93b0-4a47-b6f0-7b8195509f8a {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:42 #32661] [] DEBUG -- DirectorJobRunner: Renewing lock: lock:deployment:service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b
D, [2018-05-31T06:55:42 #32661] [] DEBUG -- DirectorJobRunner: (0.041178s) UPDATE "locks" SET "expired_at" = '2018-05-31 06:59:43.530379+0000' WHERE (("name" = 'lock:deployment:service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b') AND ("uid" = 'd77385a0-b330-4380-9b7a-9bf98274eebc'))
D, [2018-05-31T06:55:42 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.0db4f783-1dfc-43cc-be31-39deb45419e4"}
D, [2018-05-31T06:55:42 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.0db4f783-1dfc-43cc-be31-39deb45419e4 {"value":{"agent_task_id":"53ccf286-ffde-4b38-7697-2170d37fa838","state":"running"}}
D, [2018-05-31T06:55:43 #32661] [] DEBUG -- DirectorJobRunner: SENT: agent.e93b4202-1335-4330-bfe5-4978e215cc79 {"protocol":3,"method":"get_task","arguments":["53ccf286-ffde-4b38-7697-2170d37fa838"],"reply_to":"director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.e23e476d-0e00-4e05-9e56-feadbaade923"}
D, [2018-05-31T06:55:43 #32661] [] DEBUG -- DirectorJobRunner: RECEIVED: director.444af1b5-278d-4798-9699-a6ef39f2cfdc.e93b4202-1335-4330-bfe5-4978e215cc79.e23e476d-0e00-4e05-9e56-feadbaade923 {"exception":{"message":"Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check."}}
E, [2018-05-31T06:55:43 #32661] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check. - /var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:277:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:332:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:50:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:388:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:198:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:352:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:164:in `run_script'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/post_deployment_script_runner.rb:36:in `block (4 levels) in run_post_deploys_after_deployment'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-05-31T06:55:43 #32661] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.003481s) DELETE FROM "locks" WHERE (("name" = 'lock:deployment:service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b') AND ("uid" = 'd77385a0-b330-4380-9b7a-9bf98274eebc'))
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b uid: d77385a0-b330-4380-9b7a-9bf98274eebc
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000126s) BEGIN
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000742s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (NULL, '2018-05-31 06:55:43.872317+0000', 'pivotal-container-service-e53e4d347e5e339296bb', 'release', 'lock', 'lock:deployment:service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b', NULL, '120', 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b', NULL, '{}') RETURNING *
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.043147s) COMMIT
I, [2018-05-31T06:55:43 #32661] [task:120]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"0ee52c42-9144-4721-9447-4081e4971e18","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b' against Director '549e5dae-d3e4-4313-871c-9292ec9ad228': #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check.>","created_at":1527749743,"deployment":"service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b"}
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000511s) BEGIN
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000716s) INSERT INTO "events" ("parent_id", "timestamp", "user", "action", "object_type", "object_name", "error", "task", "deployment", "instance", "context_json") VALUES (876, '2018-05-31 06:55:43.926727+0000', 'pivotal-container-service-e53e4d347e5e339296bb', 'create', 'deployment', 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b', 'Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check.', '120', 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b', NULL, '{"before":{},"after":{"releases":["bosh-dns/1.3.0","pks-helpers/24.0.0","docker/30.1.104","kubo/0.13.18","kubo-etcd/9","pks-nsx-t/0.8.0","syslog-migration/10"],"stemcells":["bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.42"]}}') RETURNING *
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.003447s) COMMIT
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.002075s) SELECT * FROM "deployments" WHERE ("name" = 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b') LIMIT 1
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.004860s) SELECT * FROM "variable_sets" WHERE ("variable_sets"."deployment_id" = 4) ORDER BY "created_at" DESC LIMIT 1
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000132s) BEGIN
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.001129s) UPDATE "variable_sets" SET "writable" = false WHERE ("id" = 8)
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.003567s) COMMIT
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000385s) BEGIN
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.001307s) UPDATE "tasks" SET "event_output" = ("event_output" || '{"time":1527749743,"error":{"code":450001,"message":"Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check."}}
') WHERE ("id" = 120)
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.003690s) COMMIT
E, [2018-05-31T06:55:43 #32661] [task:120] ERROR -- DirectorJobRunner: Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check.
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:277:in `handle_method'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:332:in `handle_message_with_retry'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:50:in `method_missing'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:388:in `get_task_status'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:198:in `wait_for_task'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:352:in `send_message'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/agent_client.rb:164:in `run_script'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh-director-0.0.0/lib/bosh/director/post_deployment_script_runner.rb:36:in `block (4 levels) in run_post_deploys_after_deployment'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/bosh_common-0.0.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000576s) SELECT * FROM "tasks" WHERE ("id" = 120) LIMIT 1
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.000127s) BEGIN
D, [2018-05-31T06:55:43 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.001835s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2018-05-31 06:55:43.976670+0000', "description" = 'create deployment', "result" = 'Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs:...', "output" = '/var/vcap/store/director/tasks/120', "checkpoint_time" = '2018-05-31 06:55:39.013729+0000', "type" = 'update_deployment', "username" = 'pivotal-container-service-e53e4d347e5e339296bb', "deployment_name" = 'service-instance_0c179338-7245-4df1-824e-913f5eeb0f5b', "started_at" = '2018-05-31 05:51:33.916293+0000', "event_output" = '{"time":1527745894,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"started","progress":0}
{"time":1527745910,"stage":"Preparing deployment","tags":[],"total":1,"task":"Preparing deployment","index":1,"state":"finished","progress":100}
{"time":1527745944,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"started","progress":0}
{"time":1527745944,"stage":"Preparing package compilation","tags":[],"total":1,"task":"Finding packages to compile","index":1,"state":"finished","progress":100}
{"time":1527745944,"stage":"Creating missing vms","tags":[],"total":4,"task":"master/dc6c4011-80e7-4a9b-922e-5366033e377d (0)","index":1,"state":"started","progress":0}
{"time":1527745944,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/6d6a4f8c-4431-406e-8381-6cc2069dc860 (0)","index":2,"state":"started","progress":0}
{"time":1527745944,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/acc08d9e-4cf1-46ba-8d01-af9b9aede81a (2)","index":4,"state":"started","progress":0}
{"time":1527745944,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/411628d6-4131-452b-9e86-0ee4547a9a7b (1)","index":3,"state":"started","progress":0}
{"time":1527746099,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/411628d6-4131-452b-9e86-0ee4547a9a7b (1)","index":3,"state":"finished","progress":100}
{"time":1527746122,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/6d6a4f8c-4431-406e-8381-6cc2069dc860 (0)","index":2,"state":"finished","progress":100}
{"time":1527746124,"stage":"Creating missing vms","tags":[],"total":4,"task":"worker/acc08d9e-4cf1-46ba-8d01-af9b9aede81a (2)","index":4,"state":"finished","progress":100}
{"time":1527746134,"stage":"Creating missing vms","tags":[],"total":4,"task":"master/dc6c4011-80e7-4a9b-922e-5366033e377d (0)","index":1,"state":"finished","progress":100}
{"time":1527746134,"stage":"Updating instance","tags":["master"],"total":1,"task":"master/dc6c4011-80e7-4a9b-922e-5366033e377d (0) (canary)","index":1,"state":"started","progress":0}
{"time":1527746424,"stage":"Updating instance","tags":["master"],"total":1,"task":"master/dc6c4011-80e7-4a9b-922e-5366033e377d (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1527746424,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/6d6a4f8c-4431-406e-8381-6cc2069dc860 (0) (canary)","index":1,"state":"started","progress":0}
{"time":1527747089,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/6d6a4f8c-4431-406e-8381-6cc2069dc860 (0) (canary)","index":1,"state":"finished","progress":100}
{"time":1527747089,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/411628d6-4131-452b-9e86-0ee4547a9a7b (1)","index":2,"state":"started","progress":0}
{"time":1527747867,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/411628d6-4131-452b-9e86-0ee4547a9a7b (1)","index":2,"state":"finished","progress":100}
{"time":1527747867,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/acc08d9e-4cf1-46ba-8d01-af9b9aede81a (2)","index":3,"state":"started","progress":0}
{"time":1527748542,"stage":"Updating instance","tags":["worker"],"total":3,"task":"worker/acc08d9e-4cf1-46ba-8d01-af9b9aede81a (2)","index":3,"state":"finished","progress":100}
{"time":1527749743,"error":{"code":450001,"message":"Action Failed get_task: Task 53ccf286-ffde-4b38-7697-2170d37fa838 result: 1 of 3 post-deploy scripts failed. Failed Jobs: kubernetes-system-specs. Successful Jobs: kube-controller-manager, pks-nsx-t-resource-check."}}
', "result_output" = '', "context_id" = 'ae874da1-ce8b-445b-885f-57cab3636cfd' WHERE ("id" = 120)
D, [2018-05-31T06:55:44 #32661] [task:120] DEBUG -- DirectorJobRunner: (0.115586s) COMMIT
I, [2018-05-31T06:55:44 #32661] []  INFO -- DirectorJobRunner: Task took 1 hour 4 minutes 10.194163644000128 seconds to process.

Task 120 error

Capturing task '120' output:
  Expected task '120' to succeed but state is 'error'

Exit code 1
root@server:/home/user#

**Comment by henderjm** [comment]
Hi,

I don't think we can be much help on this issue anymore as this issue is in kubo 0.13.X and earlier. From 0.14.0 we have moved this from a post-deploy script to an errand as can be seen from this [story](https://www.pivotaltracker.com/story/show/154838510)

**Comment by seanos11** [comment]
This will be fixed in a more up to date PKS version, we do not know which one. Pivotal support will be the best place to answer this. 
Closing as fixed.

**Comment by zzenoxx** [comment]
Thanks for the lead & quick response guys 👍
