### ISSUE TITLE
error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry-incubator/kubo-release#232]
Hi i integrated kubo with uaa successsfully.

I created user and client, and get id and token from registered user and client.

Finally i create ClusterRole and ClusterRoleBinding with Uaa user, but unexpectedly i am getting this error.
kubectl get nodes
No resources found.
error: You must be logged in to the server (Unauthorized)

I attached my yaml files for your reference

[cluster.txt](https://github.com/cloudfoundry-incubator/kubo-release/files/2209563/cluster.txt)
[uaa.txt](https://github.com/cloudfoundry-incubator/kubo-release/files/2209564/uaa.txt)
[kubo-config.txt](https://github.com/cloudfoundry-incubator/kubo-release/files/2209565/kubo-config.txt)
[kubo.txt](https://github.com/cloudfoundry-incubator/kubo-release/files/2209566/kubo.txt)

Thanks in advance
Abhilash S

**Comment by abhilash07** [comment]
after checking my api-server log i find this error

Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]

Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, oidc: parse username claims "username@gmail.com": claim not present]]

but in above email i claim the username, is there any way to solve this error.

Thanks in Advance

Abhilash S

**Comment by iainsproat** [comment]
Thanks Abhilash.  Can you confirm how the user (username@gmail.com) was created in UAA (was it through the CLI)? Can you please check if it still exists in UAA?

**Comment by abhilash07** [comment]
hi @iainsproat, @alex-slynko thanks for your response, i overcome this error. If anyone encounter this error let me know. I am happy to help.

**Comment by iainsproat** [comment]
Thanks @abhilash07 - can you elaborate more on how you overcame the error?

Is there any way that CFCR (our code or documentation) could be improved to help avoid this issue in the future?

**Comment by abhilash07** [comment]
@iainsproat sure.
Step 1: First we should add user and client to uaa server
Step 2: We have to add following properties in kubo-deployment  cfcr.yml
<img width="565" alt="screen shot 2018-07-24 at 8 54 49 am" src="https://user-images.githubusercontent.com/10971841/43109035-b158ad78-8f1f-11e8-8905-c0d7c89943c6.png">
Note: username-claim=email should be "email", because kubernetes oidc api will read our uaa username@email.com by following email. 
useful Links:
https://github.com/frodenas/uaa-k8s-oidc-helper
https://github.com/micahhausler/k8s-oidc-helper

**Comment by abhilash07** [comment]
@qxing3, if you decode your uaa clinet id-token here https://jwt.io/ you can see your user email like this "email": "user@domain.com". So in kubernetes oidc api does not refer "user@domain.com" directly, It decodes your client id-token and refere to "email". so when you deploy kubo just leave username-claim=email like these.

**Comment by qxing3** [comment]
@abhilash07 Hi, it looks like I'm having the same issue you met ever.
```
$ kubectl get pods                                                                                             
No resources found.
error: You must be logged in to the server (Unauthorized)
```

Here's my configuration of oidc
```
oidc_issuer_url: https://uaa.mydomain.com:8443/oauth/token
oidc_client_id: kubo
oidc_username_claim: email
oidc_username_prefix: ""
oidc_groups_claim: ""
oidc_groups_prefix: ""
oidc_ca: |
    -----BEGIN CERTIFICATE-----
    MIIDGTCCAgGgAwIBAgIQZQXpAtdknBq4nYyxNYDwuTANBgkqhkiG9w0BAQsFADA2
    MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxDjAMBgNVBAMT
    BXVhYUNBMB4XDTE4MDMyODAzMDk0NVoXDTE5MDMyODAzMDk0NVowNjEMMAoGA1UE
    BhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQ4wDAYDVQQDEwV1YWFDQTCC
    ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK+kD64V61ndiH6tSsZg6qFM
    jSQs9apUNck3aSWv3XcmKpGE0eN1bq0nkBx5e2dh2L94DwGbQS/SAuaDg66VGKtp
    gcPiBvieRRyV9QAfPR1sfELjycSyPC43CeljVRrskAjS981uyimwG2xB4v5ALdwg
    HvOJDrsIMaFHHq+2U1n3fay1ZNW+pkZ7uFbvsohxMYbKxAxsT1XCmG4ndqnAPLhs
    dDVbx095QaMvDlZ2yOF1iDyacDWje3aLQ/R9BhlkG0wvtR37pCxxM1IVzP5JWHjD
    bVu9XOXxhBmVzRjk09z+iK5K4jJeW0dyEeygMXmkBfWDUPGDMyuZOhYe1hHihS0C
    AwEAAaMjMCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI
    hvcNAQELBQADggEBAE0tEtp/GJNBGB2IHUFW6Tmu5lHz3DUsTWyTtKc79Ixhj3fk
    4UOSF+IkbLXCh/CllrSdakrVIAoD2R3tW4dcCn2H540njHG/8CuJjtYmLNM7zTiD
    Lbw7ro39PTrQBNDVV/qgDKCT+hVp7J2+vggwGFS8jdds0rVz875G1svJW4Lccl/c
    7YVuByuDHPZSWZoCpEgSdQBDUm8VOY5XdyZEo8fXprtoU5MxnO41h6RxhAO/KdTW
    H4LdJeBRXZoxcBG3IdZ8ymYvXOEemeaKpSigqySph5xBsQk5q8n6gC096gD2Yw6a
    JsZXxw4ZXokTqxVlhQVw4BgUCkPfOWpcHjbVL98=
    -----END CERTIFICATE-----
```
The following is my uaa client id token decoded section on https://jwt.io 
```
{
  "sub": "10597cb2-3083-4fcb-93a2-4968b8071819",
  "aud": [
    "kubo"
  ],
  "iss": "https://uaa.mydomain.com/oauth/token",
  "exp": 1532760050,
  "iat": 1532673650,
  "amr": [
    "ext",
    "pwd"
  ],
  "azp": "kubo",
  "scope": [
    "openid"
  ],
  "email": "qi.xing3@xxx.com",
  "zid": "uaa",
  "origin": "ldap",
  "jti": "91b2784f55784bf68e1020d580097042",
  "previous_logon_time": 1532672137736,
  "email_verified": false,
  "client_id": "kubo",
  "cid": "kubo",
  "grant_type": "password",
  "user_name": "qi.xing3@xxx.com",
  "rev_sig": "6ec409ea",
  "user_id": "10597cb2-3083-4fcb-93a2-4968b8071819",
  "auth_time": 1532673650
}
```

**Comment by making** [comment]
@qxing3
When you use `email` claim, `email_verified` claim in your JWT token must be `true`.
Accepting an invitation mail from UAA turns `email_verified` `true`.

You can also use other claims such as `user_name`.
In this case, set `oidc_username_prefix` `"-"` to remove prefix so that you can use the email address as user's `name`.

**Comment by qxing3** [comment]
@making 

Thanks for your help. There's one more question, could you tell me how to make `email_verified` `true` ?  I just configured smtp for Cloud Foundry UAA, and I can create accounts through https://login.mydomain.com, and then I can activate the user through an invitation email, this way  the users `verified` attribute in UAA is true, but account `qi.xing3@xxx.com` exists in LDAP not uaadb, how can I make its `verified` attribute to true ?
```
→ uaac user get qi.xing3@xxx.com | grep verified
  verified: false
```

**Comment by qxing3** [comment]
@xuechao2030@icloud.com

**Comment by qxing3** [comment]
@chaoMaster

**Comment by making** [comment]
@qxing3 I'm not sure here is the right place to answer the question unrelated to cfcr.
I have no idea how you deployed cloud foundry. If you access UAA via LB -> router, you shouldn't have that issue.
I guess you are fetching UAA directly. You could solve it by adding `uaa.mydomain.com` to `/variables/name=uaa_ssl/options/alternative_names`
https://github.com/cloudfoundry/cf-deployment/blob/v3.1.0/cf-deployment.yml#L1936-L1942 
You need to delete `uaa_ssl` in credhub before applying this change.

**Comment by qxing3** [comment]
@making Got it, thanks a lot.
