### ISSUE TITLE
Add kube-dns-autoscaler

### ISSUE THREAD

**Issue by making** [cloudfoundry-incubator/kubo-release#240]
**Is your feature request related to a problem? Please describe.**

While upgrading a k8s cluster, one of my HA workload didn't work due to `UnknowHostException`. This was because of single kube-dns.
I've deployed [kube-dns-autoscaler](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns-horizontal-autoscaler) which is deployed in a GKE cluster by default.

**Describe the solution you'd like**
It would be helpful if kube-dns-autoscaler is installed via `bosh run-errand apply-addons`.

**Describe alternatives you've considered**

* Adding ops-file to include `kube-dns-autoscaler` in specs ([kubo-deployment](https://github.com/cloudfoundry-incubator/kubo-deployment))
* Supporting [CoreDNS](https://kubernetes.io/blog/2018/07/10/coredns-ga-for-kubernetes-cluster-dns/) which became GA in k8s 1.11. Not sure this issue is resolved out of the box.

**Comment by iainsproat** [comment]
Hi @making 

Thanks for raising this issue.  We've recently [added CoreDNS as an optional alternative](https://github.com/cloudfoundry-incubator/kubo-release/commit/514531d0aac4f8df2bc59bd8fd55665a93cdae7c), and should be part of the 0.21 release.

We believe CoreDNS should assist with this issue.

Out of interest, how many pods are you running and how many worker nodes do you have when you see this issue?

**Comment by alex-slynko** [comment]
Hi @making 
0.21 has an option to deploy CoreDNS as a system DNS addon. 
Could you please check if you still need the dns-autoscaler?

**Comment by making** [comment]
will do, thanks!

**Comment by making** [comment]
I've updated to 0.21 and switched to CoreDNS
I don't think just switching to CoreDNS solves this issue.
The number of replica of CoreDNS is 1 as configured in [the spec](https://github.com/cloudfoundry-incubator/kubo-release/blob/v0.21.0/jobs/apply-specs/templates/specs/coredns.yml.erb#L74).

[DNS-Autoscaler supports CoreDNS](https://github.com/kubernetes/kubernetes/pull/62409).
Configuring that made coredns HA. The manifest I used is [this](https://github.com/making/cfcr-manifests/commit/71b36bbc2edb0c34e099d63328504822c3c1d276).

I believe providing an option to enable `kube-dns-autoscaler` would be really helpful so that the DNS keeps available during k8s update.

**Comment by alex-slynko** [comment]
Thanks for the reference. I'll discuss it with @seanos11 and we will come back to you

**Comment by seanos11** [comment]
Hi @making question, is there anything you need to do to a standard CFCR deployment before you enable the DNS autoscaler?
So looking to confirm, after deploying a cluster with v0.21 (with either KubeDNS or CoreDNS), you can apply the kube-dns-autoscaler via kubectl. So this proposal is CFCR allow for this within apply-spec, so the cluster will have this already enabled when deployed (and apply-spec is run)

**Comment by addisonhuddy** [comment]
This is a downstream feature that doesn't sit in the scope of CFCR.  Closing.
