### ISSUE TITLE
Do not fail apply-specs if addons-spec is empty

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry-incubator/kubo-release#241]
**Is your feature request related to a problem? Please describe.**
kubectl fails when you apply a manifest that does not contain any objects:

```
$ echo "---" | kubectl apply -f -
error: no objects passed to apply
```

If a user provides an empty manifest, for instance `---` or whitespace. That will fail the apply-specs errand. We ran into this because OpsMan can not concatenate two values without some sort of additional characters. Additionally, if a user provides `---` it will fail which is not obvious.

**Describe the solution you'd like**
When applying specs one of three things can be done:

1. Parse the yaml first and see if contains data. There are already some empty value checks being done here: https://github.com/cloudfoundry-incubator/kubo-release/blob/42f962bb594aa3092094393560cdd38e571af698/jobs/apply-specs/spec
2. Apply the specs and if the error matches "error: no objects passed to apply" do not fail the errand.
3. Just trim whitespace from both sides of the document before doing the empty check. This would solve our issue but users that provide `---` would still fail the errand.

**Describe alternatives you've considered**
We spent a day trying to get OpsMan to craft either `null` or `""` when concatenating two empty strings. We were not able to find a way to accomplish this. Our workaround is to always have an namespace object created so that the job doesn't fail for this reason.

**Additional context**
Pretty straight forward issue.

**Comment by iainsproat** [comment]
Thanks for highlighting this @jasonkeene 

On first glance, we think the current behaviour is appropriate.  The error highlights to the user that they have passed malformed/empty spec to CFCR/kubectl, and that they would probably want to investigate as to why they are passing empty files.

I'm going to close this for now, but feel free to discuss further in the comments if you wish.

cc @karampok

**Comment by jasonkeene** [comment]
Fair enough. We've worked around this on our end by always appending a namespace.
