### ISSUE TITLE
Allow deletion in apply-specs errand

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry-incubator/kubo-release#244]
**Is your feature request related to a problem? Please describe.**
In PKS if something gets added via `addons-spec` property it can not be deleted later other than manually deleting from each cluster.

**Describe the solution you'd like**
Add a `delete-addons-spec` property would be deleted via `kubectl delete`.

**Describe alternatives you've considered**
We considered having another job/errand but, because of the way PKS and the on demand service broker works, I am of the understanding that this would require an additional VM to be created for this errand. They are not co-located. This is costly and it would be inconsistent to apply specs in one release's errand and then delete them in another release's errand.

**Additional context**
If we don't add this to the existing errand it will force another VM to be created. Cluster creation time on PKS is painfully slow already with all the errands running. I'm trying to avoid adding to the slowness.

**Comment by seanos11** [comment]
Hi @jasonkeene , may you provide an example use case/scenario on when and why you want to delete the add-on

**Comment by jasonkeene** [comment]
PKS uses apply-specs to:

1. Allow operators to add specs that they define to all clusters. An example might be the datadog daemonset. The can paste in the daemonset they are provided by datadog and it will get applied to all clusters.
1. Allow operators to enable features that PKS provides that contain kubernetes objects. This includes things such as our sink custom resource.

If the user chooses to remove some specs or disable some PKS cluster features after they have been applied to a cluster this will not work. `kubectl apply` is an upsert operation. There is effectively no way to delete something from all clusters that was added. The operator would have to manually connect to each cluster and deleting the objects.

This use case is PKS specific but I imagine this also applies to regular CFCR clusters. If a use provides a value for `addons-spec` how do you expect that they delete it once it is no longer needed?

**Comment by mordebites** [comment]
@jasonkeene we think this should be part of PKS as well as our custom addons specs because we expect operators to use kubectl directly.

You should provide this feature request to them directly.
