### ISSUE TITLE
kubelet drain script is not waiting for PVs to be detached

### ISSUE THREAD

**Issue by jostockley** [cloudfoundry-incubator/kubo-release#246]
**What happened**:
When using BOSH to update or recreate a worker node, the drain script is run for kubelet job. Currently it runs a kubectl drain ... immediately followed by kubectl delete node ...
After the kubectl drain, the pods are evicted but the PVs (vSphere vmdk files) remain attached to the VM until the controller manager detaches them, usually within a few seconds. 
However because the kubectl delete node is run immediately, the k8s master deletes all the node info so when the manager is unable to resolve the node to detach the PV.
When the scheduler tries to deploy a pod on a replacement node it cannot attach the PV because the underlying vmdk is still attached to the original deleted node.

In our case the node VM has 30-35 PV vmdks attached. It usually takes 15-20 seconds before they are all detached. If I comment out the kubectl delete node everything is fine.

**What you expected to happen**:
kubelet job drain script should either not delete the node, or should wait for the PVs to be detached.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy pods with PVs on vSphere untill there are 20 or more PVs attached to the worker node.
Use BOSH stop to stop the worker.
Observe in vCenter UI that PV vmdks are still attached to worker VM.
Also observe the errors in vCenter about unable to attach vmdk to other nodes due to locks.

**Anything else we need to know?**:
I initially commented out the kubectl delete node and that works. As an alternative it changed the drain to the following:
```bash
  echo "$(date): Kubelet draining..."
  retry drain_kubelet
  echo "$(date): checking for attached PVs..."
  ndisks=$(lsblk -dnl -o NAME,TYPE,MOUNTPOINT|awk '/vsphere-volume/ { if ( $2 == "disk" ) then; print $1, $3; endif }'|wc -l)
  while (( ndisks != 0 ))
  do
    echo "$(date): ${ndisks} still attached"
    sleep 2
    ndisks=$(lsblk -dnl -o NAME,TYPE,MOUNTPOINT|awk '/vsphere-volume/ { if ( $2 == "disk" ) then; print $1, $3; endif }'|wc -l)
  done
  echo "$(date): ${ndisks} attached"
  echo "$(date): deleting drained node..."
  retry delete_drained_node
```
And that also helped.
**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
```
Using environment '10.9.57.200' as client 'bosh_admin'

Name  Release(s)      Stemcell(s)                                       Config(s)  Team(s)
cfcr  bosh-dns/0.2.0  bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.16  -          -
      bpm/0.6.0
      cfcr-etcd/1.3
      docker/32.0.0
      kubo/0.17.0
```
- Environment Info (`bosh -e <environment> environment`):
```
Using environment '10.9.57.200' as client 'bosh_admin'

Name      bp-cfcr
UUID      8f8aa31e-4f04-4f2d-b474-53a7782156e5
Version   264.7.0 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      bosh_admin
```
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
```
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):
vSphere

**Comment by tvs** [comment]
Hey @jostockley,

Thanks for the report and the drain snippet. We've been running into similar problems on AWS as well so we made a few modifications to untie it from just vSphere. That should be in with a361b8666a2310045b21e513fd3709b862064931. 

I do think there might be one other scenario where Docker can deadlock on handling volume detachment which in turn leads to Pods not terminating. I would expect that issue to expose similar problems to what we see here. Issue [#332](https://github.com/cloudfoundry-incubator/kubo-deployment/issues/332) in kubo-deployment goes into a bit more detail about that problem.

I'll go ahead and close the issue for now, as the fix seems to have stabilized our issue in AWS. If you continue to experience the same problem, please re-open it.
