### ISSUE TITLE
 Error: Config Server returned a NON-JSON body while generating value for '/kubo-bosh/cfcr/tls-kubelet' with type 'certificate'

### ISSUE THREAD

**Issue by sdinesh116** [cloudfoundry-incubator/kubo-release#253]
**What happened**: kubo deployment failed on openstack with error message 

**_Task 10 | 06:47:34 | Preparing deployment: Preparing deployment (00:00:01)
                   L Error: Config Server returned a NON-JSON body while generating value for '/kubo-bosh/cfcr/tls-kubelet' with type 'certificate'
Task 10 | 06:47:35 | Error: Config Server returned a NON-JSON body while generating value for '/kubo-bosh/cfcr/tls-kubelet' with type 'certificate'_**

**What you expected to happen**:  successful creation kubernetes cluster  
**How to reproduce it (as minimally and precisely as possible)**: deploy bosh director with credhub uaa and config server on openstack and then deploy kubo using the following command 
`bosh deploy -d cfcr manifests/cfcr.yml -o manifests/ops-files/misc/single-master.yml   -o manifests/ops-files/add-hostname-to-master-certificate.yml -o manifests/ops-files/iaas/openstack/cloud-provider.yml -o manifests/ops-files/iaas/openstack/master-static-ip.yml -o manifests/ops-files/add-proxy.yml -o manifests/ops-files/allow-privileged-containers.yml -v api-hostname=kubo.dte.com --vars-file=vars.yml`

**Anything else we need to know?**:

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):

Name  Release(s)      Stemcell(s)  Config(s)  Team(s)
cfcr  bosh-dns/1.8.0  -            -          -
kubo/0.21.0

- Environment Info (`bosh -e <environment> environment`):
Name      kubo-bosh
UUID      22f47149-0a30-452b-941a-4a4da15d5f25
Version   266.4.0 (00000000)
CPI       openstack_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      admin

- Kubernetes version (`kubectl version`): 
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):  openstack

**Comment by iainsproat** [comment]
Hi @sdinesh116 - was the deployment manifest generated in a similar way to this issue? https://github.com/cloudfoundry-incubator/kubo-deployment/issues/345#issuecomment-422977669

**Comment by addisonhuddy** [comment]
I was not able to reproduce this issue.  If the problem persists, please reopen.
