### ISSUE TITLE
Default location of emptyDir on nodes causes root filesystem to fill

### ISSUE THREAD

**Issue by jostockley** [cloudfoundry-incubator/kubo-release#254]
**What happened**:
The location of emptyDir volumes is fixed at:
/var/lib/kubelet/pods/_POD_ID_/volumes/kubernetes.io~empty-dir
This is in the stemcell's root filesystem. The size of this is fixed at 3GB (on vsphere).
There is no option to locate emptyDir in another location such as below /var/vcap/data or /var/vcap/store

**What you expected to happen**:
Expected to have a way to configure the location of emptyDir in deployment manifest, to allow for ephemeral (or even persistent) disk use and then the size can be configured. Also allow location to be configured in deployment manifest.
**How to reproduce it (as minimally and precisely as possible)**:
Deploy pods that use emptyDir and create lots of files that use up space.

**Anything else we need to know?**:

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
```
Name  Release(s)      Stemcell(s)                                       Config(s)  Team(s)
cfcr  bosh-dns/0.2.0  bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.16  -          -
      bpm/0.6.0
      cfcr-etcd/1.3
      docker/32.0.0
      kubo/0.17.0
```
- Environment Info (`bosh -e <environment> environment`):
```
Name      bp-cfcr
UUID      8f8aa31e-4f04-4f2d-b474-53a7782156e5
Version   264.7.0 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      bosh_admin
```
- Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):
vsphere

**Comment by alex-slynko** [comment]
It is possible to configure this in the manifest now.
