### ISSUE TITLE
Kube Proxy hostname override causes service.spec.externalTrafficPolicy=Local to fail

### ISSUE THREAD

**Issue by jostockley** [cloudfoundry-incubator/kubo-release#277]
**What happened**:
When following the tutorial [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport) the client cannot connect. This appear to be the same problem as seen on azure and fixed with [this PR](https://github.com/cloudfoundry-incubator/kubo-release/pull/257). However in our case we are using vSphere Cloud Provider.

**What you expected to happen**:
Following the tutorial should work.
**How to reproduce it (as minimally and precisely as possible)**:
Using vSphere Cloud Provider, follow the tutorial  [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport) and your client will fail to connect.

**Anything else we need to know?**:
When kube-proxy starts we see the following warning in the log:
`W1106 22:08:09.857720    5712 server.go:601] Failed to retrieve node info: nodes "10.9.57.240" not found

W1106 22:08:09.857858    5712 proxier.go:306] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP`

We think there is something different/wrong with how kubelet registers the node. We see that CFCR passes 
kubelet the **--hostname-override=<IP>** to kubelet, for example:
`kubelet --allow-privileged=false --cadvisor-port=0 --cloud-provider=vsphere --cni-bin-dir=/var/vcap/jobs/kubelet/packages/cni/bin --config=/var/vcap/jobs/kubelet/config/kubeletconfig.yml --container-runtime=docker --docker-endpoint=unix:///var/vcap/sys/run/docker/docker.sock --docker=unix:///var/vcap/sys/run/docker/docker.sock --fail-swap-on=false --hostname-override=10.9.57.240 --keep-terminated-pod-volumes=false --kubeconfig=/var/vcap/jobs/kubelet/config/kubeconfig --network-plugin=cni --node-labels=spec.ip=10.9.57.240,bosh.id=262bfb3b-a9c8-4e13-a94c-a7a50a26247f,failure-domain.beta.kubernetes.io/zone=z1 --v=2`
However kubectl get nodes -o wide shows the node name hostname not the IP:
`cd252906-4f17-488e-81b2-d2d21fbdc04f   Ready     <none>    26d       v1.10.3`

This explains why kube-proxy cannot find the node name with the IP.

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
Name  Release(s)      Stemcell(s)                                       Config(s)  Team(s)
cfcr  bosh-dns/0.2.0  bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.16  -          -
      bpm/0.6.0
      cfcr-etcd/1.3
      docker/32.0.0
      kubo/0.17.0

- Environment Info (`bosh -e <environment> environment`):
Name      bp-cfcr
UUID      8f8aa31e-4f04-4f2d-b474-53a7782156e5
Version   264.7.0 (00000000)
CPI       vsphere_cpi
Features  compiled_package_cache: disabled
          config_server: enabled
          dns: disabled
          snapshots: disabled
User      bosh_admin

- Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):
vsphere

**Comment by mordebites** [comment]
Hi @jostockley,
we could reproduce the issue in 0.24 and we're not experiencing it anymore after removing the hostname-override from kubelet and kube-proxy. This commit ef1ce06f181aa0fb8b1be8af333fb2ce4994c47c is currently running in our pipeline.

We recommend upgrading your cluster to the latest release version, as we do not support older versions.

**Comment by alex-slynko** [comment]
Hi @jostockley 
We celebrated prematurely. This change breaks getting logs from the cluster. We will investigate potential solutions.

**Comment by alex-slynko** [comment]
As an alternative solution, you can try to use hostport setting for pod. This way you will skip the service altogether.

**Comment by alex-slynko** [comment]
Hi @jostockley 

We have fixed it in 0.25. It requires vSphere cloud-provider to be configured to work properly.
