### ISSUE TITLE
Deploying on bosh lite using ./bin/deploy_cfcr_lite requires kubo-release folder to be next to kubo-deployment folder

### ISSUE THREAD

**Issue by MeBNoah** [cloudfoundry-incubator/kubo-release#282]
**What happened**:
Deploying CFCR on BOSH lite using ./bin/deploy_cfcr_lite failed with:
```
Creating and uploading releases:
  - Processing release 'kubo/create':
      Reading blobs index:
        Opening file ../kubo-release/config/blobs.yml:
          open ../kubo-release/config/blobs.yml: no such file or directory 
```

**What you expected to happen**:
Deployment getting deployed without errors

**How to reproduce it (as minimally and precisely as possible)**:
Assuming that there is a bosh lite installation running:
* download https://github.com/cloudfoundry-incubator/kubo-deployment/archive/v0.24.0.zip
* extract and rename to kubo-deployment 
* `cd kubo-deployment && ./bin/deploy_cfcr_lite`

**Anything else we need to know?**:
Maybe I overlooked some information in the docs, but I did not find any hint that it is required to have kubo-release folder next to kubo-deployment folder. 

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`): deployment is not there yet
- Environment Info (`bosh -e <environment> environment`): 

Name      bosh-lite-director  
UUID      2544585f-23d4-41bd-8899-40abee7c0de8  
Version   268.3.0 (00000000)  
CPI       warden_cpi  
Features  compiled_package_cache: disabled  
          config_server: enabled  
          local_dns: enabled  
          power_dns: disabled  
          snapshots: disabled  
User      admin 

- Kubernetes version (`kubectl version`): kubectl was not involded yet
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): bosh lite

**Comment by iainsproat** [comment]
Hi @MeBNoah 

Thanks for reporting this. I've added further clarification to the documentation which will be published with the v0.25 release.

Iain
