### ISSUE TITLE
Assess and remove any deprecation warnings in CFCR with v1.13

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry-incubator/kubo-release#295]
### Why

**We should** clean up deprecation warnings
**Before** we publish a CFCR release with k8s v.13
**Because** we want to be using the latest kubernetes properties and APIs, so that it makes future upgrades more stable

**As Bonnie**
**I do not want** to see kubernetes deprecation warnings in my logs
**So that** to feel confident in my CFCR clusters, in that CFCR is applying the latest kubernetes properties and APIs

### Acceptance Criteria

From the documented list of new deprecation warnings in v1.13
We have identified which we will refactor, based on risk and assessment of the replacement
And these must be refactored

**Notes:**
* Most of the deprecations are on the client [releases page](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#deprecations-and-removals)
* Review upgrade to 1.12 were it wasn't possible to remove all warnings - https://www.pivotaltracker.com/n/projects/2093412/stories/161377371

**Comment by tvs** [comment]
This was done with the release of v0.28.0.
