### ISSUE TITLE
Upgrade CFCR to Kubernetes v1.13

### ISSUE THREAD

**Issue by bstick12** [cloudfoundry-incubator/kubo-release#296]
### Why

**As Bonnie**
**I want **to the ability to update my CFCR clusters kubernetes v1.13
**So that **my clusters are up to date

### Acceptance Criteria

```gherkin
Scenario: 
Given the latest CFCR release
When I deploy to a cluster
Then the cluster is updated to use kubernetes v1.13,
And I can run smoke tests successfully
```

Any new deprecation warnings should be listed in a comment in #295 .This is a follow up story to assess & clean these

**Notes:**
* Raise this to other downstream teams (use mailing list), so they can prepare

**Comment by tvs** [comment]
This was done with the release of v0.28.0.
