### ISSUE TITLE
HostToContainer mount propagation causes containers to fail.

### ISSUE THREAD

**Issue by JasonMorgan** [cloudfoundry-incubator/kubo-release#309]
**What happened**:

node-exporter containers failed to start with the following error: `linux mounts: path / is mounted on / but it is not a shared or slave mount`

**What you expected to happen**:

Container to start normally and run without complaining.

**How to reproduce it (as minimally and precisely as possible)**:

* Deploy a CFCR or PKS cluster
* Follow the steps to deploy kube-prometheus here, https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus
* Or alternatively just run the node-exporter daemonSet
  * ` kubectl create namespace monitoring; kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/contrib/kube-prometheus/manifests/node-exporter-daemonset.yaml `
* run `kubectl get pods --namespace monitoring'

**Anything else we need to know?**:

The fix described here, https://github.com/kubernetes/kubernetes/issues/61058#issuecomment-372764783, works perfectly.

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
Name                                                   Release(s)                               Stemcell(s)                                     Config(s)                                                                          Team(s)
service-instance_f726dba3-684c-4fd1-b19a-d62495053f7e  bosh-dns/1.10.0                          bosh-aws-xen-hvm-ubuntu-xenial-go_agent/170.24  25 cloud/pivotal-container-service-05fe620e2d05cb5fae5c                            pivotal-container-service-05fe620e2d05cb5fae5c
                                                       bpm/0.13.0                                                                               33 cloud/default
                                                       cfcr-etcd/1.8.0                                                                          1 runtime/ops_manager_dns_runtime
                                                       docker/33.0.3                                                                            2 runtime/director_runtime
                                                       harbor-container-registry/1.7.3-build.2                                                  20 runtime/pivotal-container-service-05fe620e2d05cb5fae5c-enable-pks-helpers
                                                       kubo/0.25.8                                                                              34 runtime/harbor-container-registry-ffe397cd80db0e732498-harbor-bosh-dns-aliases
                                                       nsx-cf-cni/2.3.1.10693410
                                                       pks-helpers/50.0.0
                                                       pks-nsx-t/1.19.0
                                                       pks-telemetry/2.0.0-build.113
                                                       pks-vrli/0.7.0
                                                       sink-resources-release/0.1.15
                                                       syslog/11.4.0
                                                       wavefront-proxy/0.9.0

- Kubernetes version (`kubectl version`):

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-18T11:37:06Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): AWS

**Comment by svrc-pivotal** [comment]
This can be configured in the BOSH manifest for CFCR:
https://github.com/cloudfoundry-incubator/docker-boshrelease/blob/master/jobs/docker/spec#L109
