### ISSUE TITLE
issue with provisioning claim on vsphere

### ISSUE THREAD

**Issue by SergeyMuha** [cloudfoundry-incubator/kubo-release#317]
**What happened**: When doing step 5 
###To test that the cloud provider has been configured correctly, create a simple a workload with persistence volume
I got certificate error 

VolumeMode:    Filesystem
Events:
  Type       Reason              Age                 From                         Message
  ----       ------              ----                ----                         -------
  Warning    ProvisioningFailed  36s (x38 over 71m)  persistentvolume-controller  Failed to provision v
olume with StorageClass "ci-storage": Post https://vsphere-domain:443/sdk: x509: certificate signed by unknown authority
Mounted By:  <none>

**What you expected to happen**: claim should be provisioned 

**How to reproduce it (as minimally and precisely as possible)**: do step 5 from https://github.com/cloudfoundry-incubator/kubo-release/blob/master/docs/cloud-provider.md for vsphere

**Anything else we need to know?**:

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
- Environment Info (`bosh -e <environment> environment`):
- Kubernetes version (`kubectl version`):   Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0                                                                                                 d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}                                                                                                        Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5",Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`): vsphere

Is it possible to skip ssl validation?

**Comment by tvs** [comment]
By default we deploy the [vSphere Cloud Provider](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#vsphere-cloud-config-file-for-kubernetes-version-19x-and-above) without `insecure-flag = "1"`.

It is configurable during deployment though: 
```
- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-config/Global?/insecure-flag?
  value: "1"
```

**Comment by SergeyMuha** [comment]
Thanks. I will check later.
