### ISSUE TITLE
VMs for cfcr are not created in specified folder

### ISSUE THREAD

**Issue by SergeyMuha** [cloudfoundry-incubator/kubo-release#327]
**What happened**:
I deployed cfcr on Vsphere 6.x. 
I specified folder for vcenter_vms: <vsphere.vm_folder> e.x. kubo-folder but after deployment all kubo vms are in bosh default vm folder
**What you expected to happen**:
Vms should be created in specified folder
**How to reproduce it (as minimally and precisely as possible)**:
Just deploy and check if vms are in folder

**Anything else we need to know?**:
Maybe there is a CPI limitation ... 
https://github.com/cloudfoundry/bosh-vsphere-cpi-release/issues/133

**Environment**:
- Deployment Info (`bosh -d <deployment> deployment`):
- Environment Info (`bosh -e <environment> environment`):
- Kubernetes version (`kubectl version`):
- Cloud provider (e.g. `aws`, `gcp`, `vsphere`):vsphere

What is the purpose for this variable vcenter_vms: <vsphere.vm_folder>

**Comment by tvs** [comment]
Kinda cobbling this together, but based on your use of `vcenter_vms`, you're configuring the [Kubernetes vSphere Cloud Provider](https://github.com/cloudfoundry-incubator/kubo-deployment/blob/master/manifests/ops-files/iaas/vsphere/cloud-provider.yml)

In which case, that file _does not_ control where BOSH puts VMs. That configuration is defining where VCP (Kubernetes) creates VMs during volume provisioning. It would seem that you're looking to configure the BOSH CPI instead: https://bosh.io/docs/vsphere-cpi/

**Comment by SergeyMuha** [comment]
Thanks for the explanation.
