### ISSUE TITLE
Optionally include the K8s dashboard as part of the cluster deployment

### ISSUE THREAD

**Issue by alejandrogoyen** [cloudfoundry-incubator/kubo-release#34]
Our `kubernetes-system-specs` job is now achieving two things:
1 - Installing `kubedns` which is crucial for pod-2-pod communication
2 - Installing the kubernetes dashboard UI, which can be optional

Let's split those into separate jobs, making the dashboard optional, effectively deploying it via a bosh errand.

**Comment by wdxxs2z** [comment]
Hi @alejandrogoyen 

https://github.com/pivotal-cf-experimental/kubo-deployment/issues/61
