### ISSUE TITLE
Fix mount path to point to some generic location instead of BOSH specific /var/vcap

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/kubo-release#35]
Mount path points to location inside container, we don't need to point it to `/var/vcap/...`

See https://github.com/pivotal-cf-experimental/kubo-release/blob/1b154b7d4bdbe6124d2e2b20cfc90107ba889fcf/jobs/kubernetes-system-specs/templates/config/kubedns-rc.yml#L103

**Comment by iainsproat** [comment]
@alex-slynko Is this request still required/relevant?

**Comment by alex-slynko** [comment]
Yes, it is.

We mount `kubeconfig` at /var/vcap/jobs/` path inside the container. That is pretty confusing. Because, we use this path in args, even though it can be considered as different VM.
