### ISSUE TITLE
deploy cfcr error

### ISSUE THREAD

**Issue by sunnypandas** [cloudfoundry-incubator/kubo-release#353]
Hello, guys

I used command <bosh -e vbox deploy -d cfcr manifests/cfcr.yml   -o manifests/ops-files/misc/single-master.yml   -o manifests/ops-files/add-hostname-to-master-certificate.yml   -v api-hostname=192.168.50.6> to deploy cfcr, but always 
**_Error: - Failed to find variable '/internal_gw' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'
- Failed to find variable '/internal_cidr' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'_**

I try and try but cannot find the solution for this problem, please help me.

Thank you very much.

**Comment by sppsun** [comment]
Yes, you are right. Thank you very much.
