### ISSUE TITLE
Add ability to add predictable label on worker node

### ISSUE THREAD

**Issue by obeyler** [cloudfoundry-incubator/kubo-release#368]
**Is your feature request related to a problem? 
Node names in cloud environments are not always predictable or stable.
We have on each worker node a stable label  (bosh.id) but it is not predictable
I need to create LocalPv and be sure that if the node is deleted/recreated I'll be able to recreate it.

**Describe the solution you'd like**
Add bosh index as node label

**Describe alternatives you've considered**
Do it by another bosh release

**Additional context**

**Comment by svrc-pivotal** [comment]
This addon should resolve it for now - I'll merge it in for 0.44:  https://github.com/svrc-pivotal/pks-persistent-taints-labels
