### ISSUE TITLE
while worker instance updating getting  failed kubelet jobs

### ISSUE THREAD

**Issue by lordcf** [cloudfoundry-incubator/kubo-release#379]
Hi,
I have deployed kuberenetes cluster with 3 master and 3 worker nodes while updating worker instance i am getting below error:
Error: Action Failed get_task: Task 8d96ea04-cd7b-45c1-45ab-57e81d230d7f result: 1 of 2 post-start scripts failed. Failed Jobs: kubelet. Successful Jobs: bosh-dns.

**Comment by svrc-pivotal** [comment]
Probably easiest to troubleshoot on Cloudfoundry slack cfcr channel.  

We'd need your bosh log files on the failed worker node.  (kubelet logs at minimum)
