### ISSUE TITLE
unable to build release: tls: handshake failure

### ISSUE THREAD

**Issue by obeyler** [cloudfoundry-incubator/kubo-release#380]
**What happened**:
git clone https://github.com/cloudfoundry-incubator/kubo-release.git
Cloning into 'kubo-release'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 20516 (delta 0), reused 2 (delta 0), pack-reused 20512
Receiving objects: 100% (20516/20516), 26.17 MiB | 15.07 MiB/s, done.
Resolving deltas: 100% (9816/9816), done.

$ bosh create-release --force
Blob download 'autoconf-2.69.tar.gz' (1.9 MB) (id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3 sha1: 562471cbcb0dd0fa42a76665acf0dbb68479b78a) started

Blob download 'autoconf-2.69.tar.gz' (id: 2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3) failed

- Getting blob '2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3' for path 'autoconf-2.69.tar.gz':
    Getting blob from inner blobstore:
      Getting blob from inner blobstore:
        RequestError: send request failed
caused by: Get https:/kubo-release-blobs/2e4a01bd-aa1e-4fbc-5f56-80aa40d805e3: remote error: tls: handshake failure

Exit code 1

**Comment by svrc-pivotal** [comment]
what version of BOSH CLI?   
Linux or Mac?

I'm having a hard time replicating this

**Comment by obeyler** [comment]
I found the main reason it's due to a bug on last bosh cli
./bosh-cli-6.1.1-linux-amd64 create-release --force => Works
 ./bosh-cli-6.2.0-linux-amd64 create-release --force => Failed !
 ./bosh-cli-6.2.1-linux-amd64 create-release --force => Failed !

**Comment by obeyler** [comment]
I create a bug on bosh side
