### ISSUE TITLE
As an OSS developer, I can include an existing etcd v3 bosh release as part of my kubo-release

### ISSUE THREAD

**Issue by alejandrogoyen** [cloudfoundry-incubator/kubo-release#53]

**Comment by alejandrogoyen** [comment]
Tasks needed
1) CI already exists for ETCD. Make ETCD CI public
2) Remove failing tests that are no longer needed from CI

**Comment by alex-slynko** [comment]
Tests to be removed:
1. everything consul release. We should use BOSH-dns or PowerDNS
1. rename test is not needed since we deploy on new BOSH only

Additionally, it would be nice to run tests on KuBOSH instead of custom BOSH.

On a side note, we can support only installation with TLS and thus remove upgrade from non-secure to secure cluster.

**Comment by pivotal-jwinters** [comment]
We are going to hold off on removing consul for now. The less we modify the release, the easier it will be to pull in upstream changes later on. 

Also since consul is only required when using ssl, it makes more sense to remove it when we deal with the etcd ssl issues as a whole.

**Comment by alex-slynko** [comment]
Infrastructure pipeline has bosh with 7 workers. This was breaking our current pipeline.

I changed this manually, now the `split brain one leader [It] bubbles up a failure from consistency checker to bosh` test is failing

**Comment by alex-slynko** [comment]
tests are passing now, there was problem with BOSH cleanup

**Comment by alex-slynko** [comment]
got extra debug output from develop branch of etcd release

**Comment by akshaymankar** [comment]
etcd-turbulence tests failed.
We created issue for BOSH team: https://github.com/cloudfoundry/bosh/issues/1725

**Comment by alex-slynko** [comment]
We were able to make `etcd` pipeline to pass with our environment.
Now we are working on renaming release to kubo-etcd.
Here is current pipeline for `etcd`
https://ci.kubo.sh/teams/main/pipelines/etcd/

**Comment by alex-slynko** [comment]
We are working now on etcd-v3 branch that has been rebased on top of last etcd release. Currently turbulence job of the pipeline is failing. We disabled tests for now.  As soon as CI goes green, we plan to build final release from kubo-etcd and integrate it in kubo- deployment repo.

**Comment by alex-slynko** [comment]
We have built the kubo-etcd release v2.
