### ISSUE TITLE
As an OSS developer, I can deploy Ingress Controller to create routes for my K8s applications

### ISSUE THREAD

**Issue by alejandrogoyen** [cloudfoundry-incubator/kubo-release#55]
Rationale:
-Some IAAS (e.g. Openstack) doesn't have concept of LB. Therefore an alternative way to expose app routes is needed.
- An Ingress controller can be deployed within K8 cluster, allowing user to define ingress routes to/from their services.
https://kubernetes.io/docs/concepts/services-networking/ingress/

In environments other than GCE/GKE, you need to deploy a controller as a pod.
https://github.com/kubernetes/ingress/tree/master/controllers

An Ingress Controller is a daemon, deployed as a Kubernetes Pod, that watches the apiserver's /ingresses endpoint for updates to the Ingress resource. Its job is to satisfy requests for ingress.

**Comment by pivotal-jwinters** [comment]
Looking into a certificate issue with the ingress-controller trying to talk to the api server. It seems like the proper cert is placed inside the container under /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, however it seems like the http client isn't using it.

See the link below for more info about how the client grabs credentials from the container.
https://github.com/kubernetes/ingress/blob/8cd9a5a98a74ae754525d385fb37b4f060b23050/vendor/k8s.io/client-go/rest/config.go#L320

**Comment by pivotal-jwinters** [comment]
Providing the following env variables seems to solve the problem. These should be used instead of specifying the `--apiserver-host` argument.

```
env:
- name: KUBERNETES_SERVICE_HOST
  value: <some-host>
- name: KUBERNETES_SERVICE_PORT
  value: <some-port>
```

**Comment by pivotal-jwinters** [comment]
It's important to note the ingress controller does not replace an LB that front k8s workers. Our implementation exposes the ingress controller itself using a service/nodePort. Routing to this port is still expected to be done by an LB. Application routing (L7 especially) is then possible via the ingress resource.

**Comment by alex-slynko** [comment]
Sample configuration in kubo-ci https://github.com/pivotal-cf-experimental/kubo-ci/blob/9e0e46a691e17f530271252b95991e10d42d0313/specs/ingress.yml
