### ISSUE TITLE
kubo-etcd release name same as the etcd-release

### ISSUE THREAD

**Issue by hbastosc** [cloudfoundry-incubator/kubo-release#69]
Is their any intentions in the future to change the name of the release for kubo-etcd to something else? Right now it is named etcd and this may cause conflicts with the etcd-release from which has been forked.

**Comment by alex-slynko** [comment]
This will be done as part of #53 
Currently, we use release built from this source https://github.com/pivotal-cf-experimental/kubo-etcd/tree/branch
